#!/bin/sh

alias emacs='emacsclient -t'
alias vim='nvim'
alias shutdown="shutdown -h now"
alias open="xdg-open"
alias ls="lsd"
alias cat="bat"
#alias lf="lfub"

# alias ls="ls -hN --color=auto --group-directories-first"

# Verbosity and interactivity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto"
