#! /bin/sh

# Polybar
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config window_gap          9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Borders
bspc config border_width 	  1
bspc config active_border_color   '#15539E'
bspc config focused_border_color  '#15539E'

# Application rules
bspc rule -a firefox desktop='^2'
bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Transmission-gtk desktop='^9'
bspc rule -a MEGAsync state=floating
# Satus bar rules
bspc rule -a Calcurse state=floating
bspc rule -a Pavucontrol state=floating

# Autostart

dex-autostart --autostart %
