#PATH
export NPM_PACKAGES="$HOME/.local/bin/.npm-packages"
export PATH="$PATH:/home/erick/.local/bin"
export PATH="$PATH:/home/erick/.config/local/bin"
export PATH="$PATH:$NPM_PACKAGES/bin"
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
export ANDROID_SDK_ROOT='/opt/android-sdk'
export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools/"
export PATH="$PATH:$ANDROID_SDK_ROOT/tools/bin/"
export PATH="$PATH:$ANDROID_ROOT/emulator"
export PATH="$PATH:$ANDROID_SDK_ROOT/tools/"

#XDG_DIRS
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DESKTOP_DIR="$HOME/Escritorio/"
export XDG_DOWNLOAD_DIR="$HOME/Descargas"
export XDG_TEMPLATES_DIR="$HOME/Plantillas"
export XDG_PUBLICSHARE_DIR="$HOME/Público"
export XDG_DOCUMENTS_DIR="$HOME/Documentos"
export XDG_MUSIC_DIR="$HOME/Música"
export XDG_PICTURES_DIR="$HOME/Imágenes"
export XDG_VIDEOS_DIR="$HOME/Vídeos"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh"

# Desktop portal
export XDG_CURRENT_DESKTOP=XFCE

# Qt apps theme
export QT_STYLE_OVERRIDE=highcontrast

# Java aplications
export _JAVA_AWT_WM_NONREPARENTING=1

# Tool
export EDITOR="emacsclient -a \"\" -t"
export VISUAL="emacsclient -a \"\" -t"
export TERMINAL="/usr/local/bin/st"
export BROWSER="/usr/bin/firefox"
export CHROME_EXECUTABLE="/usr/bin/firefox"
