# Enable colors and change prompt
autoload -U colors && colors	# Load colors
PS1="%B %{$fg[cyan]%}%~%{$reset_color%} $%b " # TODO: Change prompt later

# Autocd
setopt autocd
# Disable Ctrl-s to freeze terminal
# stty stop undef
# setopt interactive_comments
unsetopt PROMPT_SP

# History in cache directory:
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"

# Load aliases
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"

#Load fancy command history search with ctrl-r
source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zsh-fzf-history-search.zsh"

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
_comp_options+=(globdots)		# Include hidden files.

precmd () { printf "\e]2;%s@%s:%s\a" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}" ;}

bindkey -s '^p' '^uthunar\n'

bindkey -s '^f' '^ucd "$(dirname "$(fzf)")"\n'

bindkey '^[[3~' delete-char

# Edit line in emacs with ctrl-x ctrl-e:
autoload edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line
