#!/bin/sh

# vim shorter than nvim
alias vim='nvim'
alias vimdiff="nvim -d"
# Always human readable
alias du='du -h'
# Shorter form to move to previous directory
alias ..='cd ..'
# Go to configuration folder
alias conf='cd ~/.config/'
alias bin="cd ~/.config/local/bin/"
alias dev="cd ~/Media/Dev"
alias aur="cd ~/Media/Dev/AUR/"
alias dwn="cd ~/Media/Downloads/"
alias doc="cd ~/Media/Documents/"
alias pic="cd ~/Media/Pictures/"
alias mom="cd ~/Media/Mamá/"

# sudo not required for some system commands
for command in pacman su nethogs; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
    ywt="exec yt" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# git commands 
alias \
    gs="git status" \
    gl="git log" \
    gc="git commit -v" \
    ga="git add" \
    gd="git difftool --no-symlinks --dir-diff $1"

# Colorize commands when possible.
alias \
	ls="ls -h -F -T 0 -N -A --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
    se="sudoedit" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	y="yay" \
    # o='mimeopen -a'
	# lf="lfcd" \

# pomodoro
declare -A pomo_options
pomo_options["work"]="25"
pomo_options["break"]="5"

pomodoro () {
    if [ -n "$1" -a -n "${pomo_options["$1"]}" ]
    then
        val=$1
        printf "Now on: '$val'\n" | cat # Break pomodoro with <CR>
        sleep ${pomo_options["$1"]}m && notify-send 'Pomodoro' "'$val' session done"
    fi
}

alias wo="pomodoro 'work'"
alias br="pomodoro 'break'"

# Mount and unmount disks
dmount () {
    udisksctl mount -b "$1"
}

dunmount () {
    udisksctl unmount -b "$1"
}

# ffmpeg convertion
audioToMP3 () {
    ffmpeg -i "$1" -acodec mp3 "$1.mp3"
}

# Turn off and on the wifi
restartWlan () {
    rfkill block wlan && sleep 3s && rfkill unblock wlan && echo "Wifi reiniciado"
}

# Prettify JSON
prettyJson () {
    python -m json.tool "$1"
}

# CSV to JSON
csvToJson () {
    cat "$1" | python -c 'import csv, json, sys; print(json.dumps([dict(r) for r in csv.DictReader(sys.stdin)]))'
}

# Mimetypes
queryMime () {
    xdg-mime query "$1"
}

# Calculator
= () {
    echo "$*" | bc -l
}
