#!/bin/sh

# vim shorter than nvim
alias vim='nvim'
# Always human readable
alias du='du -h'
# Shorter form to move to previous directory
alias ..='cd ..'
# Go to configuration folder
alias conf='cd ~/.config/'
alias bin="cd ~/.config/local/bin/"
alias dev="cd /hdd0/Dev"
alias aur="cd /hdd0/Dev/AUR/"
alias dwn="cd /hdd0/Downloads/"
alias doc="cd /hdd0/Documents/"
alias pic="cd /hdd0/Pictures/"
alias mom="cd /hdd0/Mamá/"

# sudo not required for some system commands
for command in dnf su nethogs; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    yt="yt-dlp --embed-metadata -i" \
    yta="yt -x -f bestaudio/best --write-thumbnail" \
    ffmpeg="ffmpeg -hide_banner"

# git commands 
alias \
    gs="git status" \
    gl="git log" \
    gc="git commit -v" \
    ga="git add" \
    gd="git difftool --no-symlinks --dir-diff $1"

# Colorize commands when possible.
alias \
    ls="ls -h -F -T 0 -N -A --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    g="git" \
    sdn="shutdown -h now" \
    se="sudoedit" \
    e="$EDITOR" \
    v="$EDITOR" \
    o='xdg-open' \
    lf='lfcd'

# Mount and unmount disks
dmount () {
    udisksctl mount -b "$1"
}

dunmount () {
    udisksctl unmount -b "$1"
}

# ffmpeg convertion
audioToMP3 () {
    ffmpeg -i "$1" -acodec libmp3lame "$1.mp3"
}

# Turn off and on the wifi
restartWlan () {
    rfkill block wlan && sleep 3s && rfkill unblock wlan && echo "Wifi reiniciado"
}

# Prettify JSON
prettyJson () {
    python -m json.tool "$1"
}

# CSV to JSON
csvToJson () {
    cat "$1" | python -c 'import csv, json, sys; print(json.dumps([dict(r) for r in csv.DictReader(sys.stdin)]))'
}

function gbll(){
    local tags branches target
    branches=$(
      git --no-pager branch --sort=-committerdate \
        --format="%(if)%(HEAD)%(then)%(else)%(if:equals=HEAD)%(refname:strip=3)%(then)%(else)%1B[0;34;1mbranch%09%1B[m%(refname:short)%(end)%(end)" \
      | sed '/^$/d') || return
    tags=$(
      git --no-pager tag | awk '{print "\x1b[35;1mtag\x1b[m\t" $1}') || return
    target=$(
      (echo "$branches"; echo "$tags") |
      fzf --no-hscroll --no-multi -n 2 \
          --ansi --preview="git --no-pager log -150 --pretty=format:%s '..{2}'") || return
    git checkout $(awk '{print $2}' <<<"$target" )
}
