#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH="$PATH:/home/erick/.local/bin"
export PATH="$PATH:/home/erick/.config/local/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DESKTOP_DIR="/hdd0/Escritorio/"
export XDG_DOWNLOAD_DIR="/hdd0/Descargas"
export XDG_TEMPLATES_DIR="/hdd0/Plantillas"
export XDG_PUBLICSHARE_DIR="/hdd0/Público"
export XDG_DOCUMENTS_DIR="/hdd0/Documentos"
export XDG_MUSIC_DIR="/hdd0/Música"
export XDG_PICTURES_DIR="/hdd0/Imágenes"
export XDG_VIDEOS_DIR="/hdd0/Vídeos"
NPM_PACKAGES="$XDG_DATA_HOME/bin/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin"

export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"
export TERMINAL="/usr/bin/kitty"
export BROWSER="/usr/bin/firefox"

export PATH="$PATH:/opt/android-studio/bin"
export PATH="$PATH:/opt/flutter/bin"
export ANDROID_HOME='~/Android/Sdk/'
export PATH=$PATH:$ANDROID_HOME/platform-tools/
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin/
export PATH=$PATH:$ANDROID_HOME/emulator

export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME=qt5ct

export INPUTRC="/home/erick/.config/bash/inputrc"
export HISTFILE="/home/erick/.cache/bash/history"
export HISTFILESIZE=20000
export HISTSIZE=20000
export HISTCONTROL="ignoredups:ignorespace"
