#!/bin/sh

# PATH
export PATH="$PATH:/home/erick/.local/bin"
export PATH="$PATH:/home/erick/.config/local/bin"
# ESPECIAL DIRS
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="/hdd0/Descargas"
export XDG_TEMPLATES_DIR="$HOME/Plantillas"
export XDG_PUBLICSHARE_DIR="$HOME/Público"
export XDG_DOCUMENTS_DIR="/hdd0/Documents"
export XDG_MUSIC_DIR="/hdd0/Music"
export XDG_PICTURES_DIR="/hdd0/Pictures"
export XDG_VIDEOS_DIR="/hdd0/Videos"

# TOOLS
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export TERMINAL="/usr/bin/xfce4-terminal"
export BROWSER="/usr/bin/firefox"
