#!/bin/sh

# PATH
export PATH="$PATH:/home/erick/.local/bin"
export PATH="$PATH:/home/erick/.config/local/bin"
# ESPECIAL DIRS
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="/media/erick/MEDIA/Descargas"
export XDG_TEMPLATES_DIR="$HOME/Plantillas"
export XDG_PUBLICSHARE_DIR="$HOME/Público"
export XDG_DOCUMENTS_DIR="/media/erick/MEDIA/Documents"
export XDG_MUSIC_DIR="/media/erick/MEDIA/Music"
export XDG_PICTURES_DIR="/media/erick/MEDIA/Pictures"
export XDG_VIDEOS_DIR="/media/erick/MEDIA/Videos"

# TOOLS
export EDITOR="$(which nvim)"
export VISUAL="$(which nvim)"
export TERMINAL="$(which kitty)"
export BROWSER="/usr/bin/firefox"
